version: "3.0"
services:
  db:
    container_name: pg_container
    image: postgres
    env_file:
      - database.env # configure postgres
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
        restart: unless-stopped

